[package]
name = "mnemonic"
version = "0.1.0"
authors = ["Daniel Akhterov <akhterovd@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "0.2.36"
hmac = "0.10.1"
sha2 = "0.9.3"
hex = "0.4.2"
